### ISSUE TITLE
Typo in README.md

### ISSUE THREAD

**Issue by Sriparno08** [srivastavaritik/Extraspace-Cloud#100]
I have noticed a typo in README.

![Screenshot 2023-05-23 212034](https://github.com/srivastavaritik/Extraspace-Cloud/assets/89148144/5838a8ef-c093-4707-9720-9984e1031218)

Fix:

`account` -> `accounts`

**Comment by Sriparno08** [comment]
I would like to work on this as part of GSSoC'23.

**Comment by Snigdha2712** [comment]
There are many extra spaces in the README.md file. Kindly assign this issue to me under gssoc23. @srivastavaritik
