### ISSUE TITLE
 create a landing page for the website 

### ISSUE THREAD

**Issue by srivastavaritik** [srivastavaritik/Extraspace-Cloud#12]
It should be a Landing page which can be referred to as homepage where all the links such as of login, sign up, about etc, options will e there. You can make a design of your choice but make sure to follow the blue and dark theme of the website.

**Comment by sachin2709** [comment]
I want to work on this task,Please assign it to me @srivastavaritik

**Comment by srivastavaritik** [comment]
@sachin2709 , okay you can work on this

**Comment by sachin2709** [comment]
sir can  I use HtML for making Landing page @srivastavaritik

**Comment by Ankur-Sh** [comment]
i want to work on this project

**Comment by sachin2709** [comment]
![Screenshot (4017)](https://user-images.githubusercontent.com/96466673/193424364-08d376cb-af46-4d39-b08a-542fa4979dd5.png)
![Screenshot (4018)](https://user-images.githubusercontent.com/96466673/193424371-aeb9e821-c981-43e2-b759-f2ebbedd4136.png)


Sir @srivastavaritik  ,I have done this ,Can I make Pull Request ??

**Comment by sachin2709** [comment]
Pls check my pull request sir @srivastavaritik

**Comment by srivastavaritik** [comment]
> Pls check my pull request sir @srivastavaritik

I think you have made this in HTML. right?

**Comment by sachin2709** [comment]
Yes Sir @srivastavaritik

**Comment by srivastavaritik** [comment]
the page you made is very good, can you do it in react?

**Comment by sachin2709** [comment]
Sorry Sir I dont have knowledge of react  now @srivastavaritik

**Comment by sachin2709** [comment]
Sir  @srivastavaritik , Will my Work be Acceptable ??

**Comment by srivastavaritik** [comment]
This was to be done in React only, but since you have made effort, I'll merge it and assign someone else to make that in react

**Comment by sachin2709** [comment]
Thankyou so much sir @srivastavaritik , it will be a great motivation for me as a begginer :)

**Comment by sachin2709** [comment]
Sir @srivastavaritik , please merge my PR

**Comment by srivastavaritik** [comment]
> Sir @srivastavaritik , please merge my PR
