### ISSUE TITLE
Fix Typo in README

### ISSUE THREAD

**Issue by Sriparno08** [srivastavaritik/Extraspace-Cloud#124]
I have noticed a typo in README.

![Screenshot 2023-06-01 103548](https://github.com/srivastavaritik/Extraspace-Cloud/assets/89148144/47fc789a-c89a-45ad-9444-e2d2dae8491a)

Fix:

`does no` -> `does not`

I would like to contribute as part of GSSoC'23.

**Comment by srivastavaritik** [comment]
Hi @Sriparno08 , you can work on this
