### ISSUE TITLE
implement dark mode toggle for the website

### ISSUE THREAD

**Issue by srivastavaritik** [srivastavaritik/Extraspace-Cloud#13]
You can design as you like

**Comment by DavidRod1865** [comment]
Hello! I'll like to work on this issue.

**Comment by asifurrahaman754** [comment]
hello @srivastavaritik, i have gone through your codebase, i would like to work on this.

**Comment by srivastavaritik** [comment]
@DavidRod1865 I have assigned you this topic, you can work on this.

**Comment by srivastavaritik** [comment]
> hello @srivastavaritik, i have gone through your codebase, i would like to work on this.

hey @asifurrahaman754 , maybe you can find some more bugs or you can work on forgot password page as @DavidRod1865 has replied early so I have to assign him this task

**Comment by asifurrahaman754** [comment]
Alright, first let me check

**Comment by asifurrahaman754** [comment]
@srivastavaritik please assign it to me, i would like to work on that

**Comment by srivastavaritik** [comment]
@DavidRod1865 Are you working on this?

**Comment by asifurrahaman754** [comment]
Hey @srivastavaritik if @DavidRod1865 not working on this, can i take it?

**Comment by DavidRod1865** [comment]
@srivastavaritik Apologies - yes, I was working on it but it may be too much for me. You can pass it along to @asifurrahaman754. Sorry for the delayed response.

**Comment by srivastavaritik** [comment]
@asifurrahaman754 you can start working on this

**Comment by asifurrahaman754** [comment]
Ok

**Comment by srivastavaritik** [comment]
@asifurrahaman754 what's the progress?

**Comment by asifurrahaman754** [comment]
@srivastavaritik first I'll have to change some css to that the color does not break, i need some time.

**Comment by srivastavaritik** [comment]
Okay, take your time.

**Comment by asifurrahaman754** [comment]
@srivastavaritik suddenly my laptop crashed with some unknown issue and it took some time to repair it, that's why I was not able to work on this issue, I'll start working on this ASAP if you haven't.

**Comment by srivastavaritik** [comment]
Okay, you can work

**Comment by asifurrahaman754** [comment]
pr for this issue #48

**Comment by codesfromvikrant** [comment]
Hey @srivastavaritik, I have reviewed the code base, and I'm confident that I can implement the dark mode toggle feature. Could you please assign me this task? I assure you that I can complete it within the next two days.

**Comment by srivastavaritik** [comment]
Hi, @codesfromvikrant , you can work on this and please refer to the Contribution guidelines on the readme once. 
All the best!

**Comment by codesfromvikrant** [comment]
Thanks @asifurrahaman754

**Comment by srivastavaritik** [comment]
I've shared an item with you:

SBI Gen AI Intermediate B2
https://drive.google.com/drive/folders/1EP_aMpnoYpT0xgqqlUg4el2dF-xODQl6?usp=sharing&ts=6a72d915

It's not an attachment -- it's stored online. To open this item, just click  
the link above.
