### ISSUE TITLE
The text "Click to change name" in the profile section

### ISSUE THREAD

**Issue by mukul314** [srivastavaritik/Extraspace-Cloud#133]
Currently the text on the profile page  "Click to change name" is not visible, we can change it's color to make it more visible.

See the below image for more context:

<img width="214" alt="2023-06-06 08_56_07-ExtraSpace - Brave" src="https://github.com/srivastavaritik/Extraspace-Cloud/assets/76463001/d04a6e2e-8b59-4736-aa7e-ae1aeead1954">

**Comment by srivastavaritik** [comment]
hi @mukul314 , you an work on this
