### ISSUE TITLE
Correction in Readme file

### ISSUE THREAD

**Issue by Yashika-Agrawal** [srivastavaritik/Extraspace-Cloud#135]
To correct minor grammatical errors in readme file. [GSsoc'23]

**Comment by srivastavaritik** [comment]
Hi @Yashika-Agrawal , can you please elaborate on what type of corrections you want to make.

**Comment by Yashika-Agrawal** [comment]
![image](https://github.com/srivastavaritik/Extraspace-Cloud/assets/97408966/c6e8e8ac-c584-48f2-89ee-2164bcbdd71d)
adviced -> advised , removing own , adding->add , improving->improve
![image](https://github.com/srivastavaritik/Extraspace-Cloud/assets/97408966/2cbccb35-aa02-4895-92cb-667cfb05f61a)
![image](https://github.com/srivastavaritik/Extraspace-Cloud/assets/97408966/b33f25a7-2788-4aac-b1e4-7598a1a7e445)
![image](https://github.com/srivastavaritik/Extraspace-Cloud/assets/97408966/90d8edbe-898c-4b73-9769-6b752dfa7b7d)
to->with 
Minor grammatical errors I want to fixed and to remove redundant commas.

**Comment by Yashika-Agrawal** [comment]
Hey @srivastavaritik , please assign me this under GSsoc'23 tag.
