### ISSUE TITLE
Popup before deleting a file

### ISSUE THREAD

**Issue by Yashika-Agrawal** [srivastavaritik/Extraspace-Cloud#136]
I want add a popup stating, 'are you sure you want to delete this file', after clicking delete button, so that the file don't get deleted accidently.

**Comment by srivastavaritik** [comment]
Hi @Yashika-Agrawal , you can work on this.

**Comment by sshiwangi** [comment]
Hey @srivastavaritik, If it's not done yet, Can I work on this issue under GSSOC'23?
