### ISSUE TITLE
Recreate landing page in Reactjs

### ISSUE THREAD

**Issue by srivastavaritik** [srivastavaritik/Extraspace-Cloud#16]
Recreate the landing page made in #15 in React. 
Make this in src folder only

**Comment by immayurpanchal** [comment]
Is anyone working on this? If not, would you please assign this to me?

**Comment by immayurpanchal** [comment]
@srivastavaritik ,
Is anyone working on this? If not, would you please assign this to me?

**Comment by srivastavaritik** [comment]
@immayurpanchal you may work on this

**Comment by immayurpanchal** [comment]
@srivastavaritik , I'm almost done with the changes. I'm stuck in minor issue. Any lead would be really helpful. Added screenshot with detailed description in the PR.
