### ISSUE TITLE
 Adding Password Visibility Toggle for Improved User Experience

### ISSUE THREAD

**Issue by Nishitbaria** [srivastavaritik/Extraspace-Cloud#163]
The addition of a password visibility toggle, in the form of a view button, within password input fields enhances the user experience. It allows users to easily toggle between hiding and revealing password characters, providing convenience, confidence, and ease of use, particularly on mobile and touch devices. This feature also considers accessibility needs and requires consistent iconography, secure input handling, user preference persistence, and cross-browser compatibility.

**Comment by Nishant4coding** [comment]
@Nishitbaria kindly assign this issue to me as GSSOC contributor
