### ISSUE TITLE
Change logo font

### ISSUE THREAD

**Issue by srivastavaritik** [srivastavaritik/Extraspace-Cloud#20]
![image](https://user-images.githubusercontent.com/78131705/193846504-2a269935-88d3-41dd-8b56-e8f4a24103d9.png)
change the link with the link given below
`<link href="https://fonts.googleapis.com/css2?family=Dancing+Script:wght@500&display=swap" rel="stylesheet"> `

And change the font-family of navbar.brand class in index.html file to the font given below:
` font-family: 'Dancing Script', cursive;`

**Comment by AKD-01** [comment]
I think I can do this, please assign me this issue
