### ISSUE TITLE
improve profile page

### ISSUE THREAD

**Issue by srivastavaritik** [srivastavaritik/Extraspace-Cloud#21]
![image](https://user-images.githubusercontent.com/78131705/193847659-4b7eab55-4606-4174-aefd-d2f1e684d73a.png)
 give some margin top to this card and bring this in middle of the page

**Comment by AKD-01** [comment]
Please assign me this issue

**Comment by sunidhisachan** [comment]
@srivastavaritik I can try this . Please assign this to me as well.

**Comment by joanjeremiah** [comment]
@srivastavaritik I have made the required changes, Kindly look into my pull request.
