### ISSUE TITLE
Navbar and footer is missing in Forgotpassword page

### ISSUE THREAD

**Issue by hs-07** [srivastavaritik/Extraspace-Cloud#30]
@srivastavaritik 
In addition, I also wanted to work over recreating the navbar and and footer.
Assign the issue to me and label it as "Hacktoberfest".

**Comment by srivastavaritik** [comment]
@hs-07 you can work on this

**Comment by hs-07** [comment]
@srivastavaritik 
hey!!
I have reacreated navbar and footer + made all necessary changes.
Here is the sample screenshot:
![image](https://user-images.githubusercontent.com/87127387/194615824-7ea42d9b-739b-4944-8c41-3fb910e6acda.png)


I just want that as soon as I make PR, U merge it within 5min becoz i wanted the badge over my profile so let me know when you are ready to merge. 
Thankyou

**Comment by srivastavaritik** [comment]
@AKD-01 please have a look

**Comment by hs-07** [comment]
@srivastavaritik 
I can make changes ,if any changes would be required afterwards also

**Comment by srivastavaritik** [comment]
@hs-07 , once @AKD-01 reviews this I'll tell you the time for pull request. First can you please send the screenshot on mobile version

**Comment by hs-07** [comment]
mobile view

![image](https://user-images.githubusercontent.com/87127387/194621863-ec3ccb04-f5e7-433e-bd4b-21f96a46f92d.png)

**Comment by srivastavaritik** [comment]
hey, @hs-07 you can raise a pull request now

**Comment by hs-07** [comment]
ok

**Comment by hs-07** [comment]
issue resolved
