### ISSUE TITLE
Improve About Page.

### ISSUE THREAD

**Issue by AKD-01** [srivastavaritik/Extraspace-Cloud#32]
![image](https://user-images.githubusercontent.com/83454075/194687868-02c4d309-2968-459d-a476-e7690043021e.png)
Click on the "About App" button to open the page and improve its styling and make it look more attractive.

**Comment by amansingh1373** [comment]
@AKD-01 i think i can do this task kindly assign me this task

**Comment by najeebkp** [comment]
Hi @amansingh1373 please assign me this task.

**Comment by debopriyadey** [comment]
@AKD-01 ill be happy to contribute. You can assign this to me.

**Comment by Agrimaagrawal** [comment]
I want to work on this ,please assign it to me

**Comment by srivastavaritik** [comment]
@debopriyadey you can work on this

**Comment by debopriyadey** [comment]
Just a follow up can i use this as the bg image for about section.
![about design](https://user-images.githubusercontent.com/64556550/194742174-9774e6b6-55c5-4a9a-920b-16fb5e990f41.jpg)

**Comment by srivastavaritik** [comment]
Yes, you can

**Comment by srivastavaritik** [comment]
yes I have merged it.
