### ISSUE TITLE
fix styling issue

### ISSUE THREAD

**Issue by srivastavaritik** [srivastavaritik/Extraspace-Cloud#42]
set flex-wrap to wrap and other respective changes and make it look good and it should not overflow
![image](https://user-images.githubusercontent.com/78131705/196033925-d4209f5a-3e4c-4841-b323-4952c4b42ea0.png)

you can reproduce this by clicking on `Developers` in mobile mode or small screen sizes

**Comment by sandilya27** [comment]
I want to work on this.
can you assign it to me?
