### ISSUE TITLE
Add a 404 not found page [GSSoC'23]

### ISSUE THREAD

**Issue by Sukhendu2002** [srivastavaritik/Extraspace-Cloud#52]
Can you assign this to me, I want to work on this under GSSoC'23

**Comment by dhruv8433** [comment]
can you assign this issue to me ?

**Comment by dhruv8433** [comment]
i have completed this issue...

**Comment by dhruv8433** [comment]
![image](https://github.com/srivastavaritik/Extraspace-Cloud/assets/114583978/3714da13-baec-4b6c-98ef-ab881c3e4e8a)

**Comment by Akshit-Nandan** [comment]
Hey I would like to work on this issue under GSSoC'23. Can you assign it to me.

**Comment by Swetha-Baskaran** [comment]
Hey, I would like to work on this issue.
Please assign this to me under the GSSOC'23 label.

**Comment by srivastavaritik** [comment]
Hi @dhruv8433 , please make a branch and raise a pr

**Comment by dhruv8433** [comment]
@srivastavaritik Done, created a pull request
