### ISSUE TITLE
Improve styling for the login/signup page gssoc'23

### ISSUE THREAD

**Issue by karthiknadar1204** [srivastavaritik/Extraspace-Cloud#53]

**Comment by karthiknadar1204** [comment]
I would like to work on this issue under gssoc'23,please assign it to me

**Comment by srivastavaritik** [comment]
Hi, @karthiknadar1204 you can work on this and please refer to the Contribution guidelines on the readme once. 
All the best!

**Comment by karthiknadar1204** [comment]
Thank you

**Comment by karthiknadar1204** [comment]
Will submit pr for the same today @srivastavaritik again
