### ISSUE TITLE
make the downloaded folder link look more prominent,

### ISSUE THREAD

**Issue by karthiknadar1204** [srivastavaritik/Extraspace-Cloud#54]
The folder image for the added document look small and unattractive,we can increase the size of the card and add hover effects to the download and delete buttons as well

**Comment by karthiknadar1204** [comment]
I would lik to work on this issue under gssoc'23

**Comment by srivastavaritik** [comment]
Hi, @karthiknadar1204 you can work on this and please refer to the Contribution guidelines on the readme once. 
All the best!

**Comment by karthiknadar1204** [comment]
Thank you,will start working asap

**Comment by karthiknadar1204** [comment]
Have started work on this issue @srivastavaritik ,Will keep updated

**Comment by karthiknadar1204** [comment]
<img width="1446" alt="Screenshot 2023-05-21 at 11 38 07 AM" src="https://github.com/srivastavaritik/Extraspace-Cloud/assets/95973644/20dfd5f0-3c04-4bf3-8ae6-5df533f3c138">
<img width="1452" alt="Screenshot 2023-05-21 at 11 38 18 AM" src="https://github.com/srivastavaritik/Extraspace-Cloud/assets/95973644/83099f8c-7a98-4a39-9470-140ba9a1d970">
<img width="1447" alt="Screenshot 2023-05-21 at 11 38 50 AM" src="https://github.com/srivastavaritik/Extraspace-Cloud/assets/95973644/d52657ed-d33f-4d30-94e6-da3ca781c2a0">

I tried setting up the project by running npm i first and when i ran npm start,this showed up and the project page is completely blank

**Comment by karthiknadar1204** [comment]
How do i proceed @srivastavaritik

**Comment by srivastavaritik** [comment]
hi @karthiknadar1204 , I tried installing and running it, it works completely fine. You may join with google meet if issue still persists

**Comment by karthiknadar1204** [comment]
@srivastavaritik thank you so much for replying,the project works fine now,i also made a pr yesterday, there were some conflicts so couldn't proceed but working on it and will retry fir this issue as well as for the pr.

Had my exams going on so was a little tight on schedule

**Comment by kaashikaagrawal** [comment]
if this issue is still open can I be assigned to work on it?
