### ISSUE TITLE
add readme badges

### ISSUE THREAD

**Issue by S-ishita** [srivastavaritik/Extraspace-Cloud#56]
I want to add readme badges.Please assign this issue to me under GSSOC
![badges](https://github.com/srivastavaritik/Extraspace-Cloud/assets/104543751/54795030-cb4f-4a88-bb43-7c59a965034b)

**Comment by srivastavaritik** [comment]
Hi, @S-ishita , you can work on this and please refer to the Contribution guidelines on the readme once. 
All the best!
