### ISSUE TITLE
validation of strong password

### ISSUE THREAD

**Issue by Nirbhay97** [srivastavaritik/Extraspace-Cloud#57]
currently, it accepts even weak password, considering the nature of application, users has to have strong passwords

**Comment by Swetha-Baskaran** [comment]
I wish to work on this.  Will anyone assign it to me?

**Comment by srivastavaritik** [comment]
> currently, it accepts even weak password, considering the nature of application, users has to have strong passwords

Hi @Nirbhay97 , do you want to work on this issue or I assign @Swetha-Baskaran .

**Comment by thestarsahil** [comment]
@srivastavaritik Hey Ritik, I have reviewed the entire repository and I am interested in working on strengthening password authentication. Since I have prior experience in this field, I am confident that I can handle this project. I would like to showcase my potential in this area.

**Comment by Nirbhay97** [comment]
hey ritik

i will be working on this, thats why i created the issue

nirbhay

**Comment by Nirbhay97** [comment]
hi @srivastavaritik , i will be working on this issue, kindly assign this to me, i created this issue for this reason only.
regards

**Comment by Nirbhay97** [comment]
please assign it with gssoc label itself. thanks
