### ISSUE TITLE
Make a page showing all the developers contributing to this repo.

### ISSUE THREAD

**Issue by srivastavaritik** [srivastavaritik/Extraspace-Cloud#6]
**Remove this developer section and instead make a button named `Developers`, which on clicking opens a Modal showing all the developers**
![image](https://user-images.githubusercontent.com/78131705/193340752-be427ee3-04df-418f-8d6d-03b1f16616dd.png)

**Comment by nirajacharyaa** [comment]
Please assign this task to me.

**Comment by srivastavaritik** [comment]
Okay I am assigning you this task.
