### ISSUE TITLE
Add Code_Of_Conduct

### ISSUE THREAD

**Issue by parthpathakpp1** [srivastavaritik/Extraspace-Cloud#60]
Code_Of_Conduct should be there .

**Comment by parthpathakpp1** [comment]
assign this issue to me .

**Comment by AKD-01** [comment]
Hi, @parthpathakpp1 , you may work on this and please refer to the Contribution guidelines on the readme once.
All the best!

**Comment by parthpathakpp1** [comment]
> 

can I directly make changes in readme.md as it is just a text or I will have to install it in my local machine and then Do it???

**Comment by ImranNawar** [comment]
Hi there!
I would like to work on this issue. @AKD-01 @parthpathakpp1 

Thank you!
