### ISSUE TITLE
Recreate About page

### ISSUE THREAD

**Issue by srivastavaritik** [srivastavaritik/Extraspace-Cloud#9]
![image](https://user-images.githubusercontent.com/78131705/193341529-54f37ef3-4ab0-4f64-8f89-942e1fa7f709.png)
 Clicking this button opens another page which is written in HTML(For code reference: https://github.com/srivastavaritik/extraspace-about)
**Setup Routing and recreate the page in ReactJs.**
**You can also do some customization to make the page look attractive.**

**Comment by srivastavaritik** [comment]
> I would love to take a look at this issue, but the link provided leads to a 404 page

Now the link is working, I have made it public. Please have a look and if you are working on this, please comment to this thread, I will assign you the task.

**Comment by asifurrahaman754** [comment]
@srivastavaritik please assign it to me

**Comment by Ankur-Sh** [comment]
i like to ontribute in this project pls assign to me

**Comment by Ankur-Sh** [comment]
i like to contribute in this project pls assign it to me

**Comment by srivastavaritik** [comment]
@asifurrahaman754 are you working on this?

**Comment by asifurrahaman754** [comment]
Yes

**Comment by asifurrahaman754** [comment]
@srivastavaritik i think my Work will be done for this isuue until tomorrow if not today, but could u add me this issue under hacktoberfest-accepted labe?

**Comment by srivastavaritik** [comment]
this issue is already having `hacktoberfest`  label, `hacktoberfest-accepted` label will be assigned only after the pull request get merged

**Comment by asifurrahaman754** [comment]
Ok got that

**Comment by srivastavaritik** [comment]
Sorry I closed this mistakenly

**Comment by asifurrahaman754** [comment]
@srivastavaritik check my pr #18

**Comment by srivastavaritik** [comment]
merged

> @srivastavaritik check my pr #18
